@host=http://localhost:8080

### Get players
GET {{host}}/api/v1/players HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IndTNE56REdEYzFxZmxnYmk3MldvdiJ9.eyJodHRwczovL2F1dGgudG4uY28udWsvcm9sZXMiOlsiYWRtaW4iXSwiaXNzIjoiaHR0cHM6Ly9kZXYtYzUxNWl3NDBwdHRpZTNzMC51cy5hdXRoMC5jb20vIiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMTI5MDIyOTI2MzE3MDI5OTA1MDMiLCJhdWQiOlsiaHR0cHM6Ly9hcGkucmFja2V0LmNvbSIsImh0dHBzOi8vZGV2LWM1MTVpdzQwcHR0aWUzczAudXMuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTc0MDcyODc5OCwiZXhwIjoxNzQwODE1MTk4LCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwiYXpwIjoiR0FEUnY1ZjN0WXgzTnNrNWJoWFBUNDdaZXJldVlxQXIifQ.FdircUEmUMaVjPL12QiGEMaZafBtY9jMjgMYmxr0iZeU2da16OrGD_KIoL8CDHfFgCAropHmws_WftPwbIzzTbhNJMJpqIfIBFYE5D6BSn7_hSGCkvOLesESEq-hLEwmXqx8c97EN_f3XvnwY5IhEqc54qo-SXNNKK2fp9-yE_7gpCko5oVXy2aoVOC6GYFd2aMexayH8EKD7K8bTblqeEyGa4DgXujVD8cCOB61hEHvCgh3mOQxCDIsQ-oIH54Ev9hKVoLfxVKGpITtbh_QQgqAIxk_8rMnkdJm8u931bzlWLmHrhFCDObwa99rmaehJvVBBNTuG4PfpQaM0GvU-A